export type DeepDivePrefabTopic = {
  concept: string;
  source: 'Hematology' | 'Pulmonology';
};

export const deepDivePrefabTopics: DeepDivePrefabTopic[] = [
  { concept: 'Coagulation cascade', source: 'Hematology' },
  { concept: 'Hemolytic Anemias', source: 'Hematology' },
  { concept: 'Sickle Cell Disease', source: 'Hematology' },
  { concept: 'DIC', source: 'Hematology' },
  { concept: 'Von Willebrand Disease', source: 'Hematology' },
  { concept: 'Introduction to Hematology & Methods in Hematopathology', source: 'Hematology' },
  { concept: 'Hematopoiesis & Stem Cell Failure', source: 'Hematology' },
  { concept: 'The Red Blood Cell', source: 'Hematology' },
  { concept: 'Nutritional Anemias & Porphyrias', source: 'Hematology' },
  { concept: 'The Thalassemias and Enzymopathies', source: 'Hematology' },
  { concept: 'Laboratory Techniques in Hematology', source: 'Hematology' },
  { concept: 'Intro to White Blood Cells and Heme Malignancies', source: 'Hematology' },
  { concept: 'Myeloproliferative Neoplasms', source: 'Hematology' },
  { concept: 'MDS/PNH', source: 'Hematology' },
  { concept: 'ALS Myeloproliferative Disorders', source: 'Hematology' },
  { concept: 'Exam 1 Review', source: 'Hematology' },
  { concept: 'Acute Leukemias', source: 'Hematology' },
  { concept: 'Lymphomas', source: 'Hematology' },
  { concept: 'HSCT and CART', source: 'Hematology' },
  { concept: 'Plasma Cell Dyscrasias', source: 'Hematology' },
  { concept: 'Plasma Cell Dyscrasias ALS', source: 'Hematology' },
  { concept: 'Morphology', source: 'Hematology' },
  { concept: 'Normal Hemostasis', source: 'Hematology' },
  { concept: 'Hereditary Bleeding Disorders', source: 'Hematology' },
  { concept: 'Acquired Bleeding Disorders', source: 'Hematology' },
  { concept: 'Morphology Active Learning Session', source: 'Hematology' },
  { concept: 'Principles of Transfusion', source: 'Hematology' },
  { concept: 'Thrombosis and Antithrombotic Therapy', source: 'Hematology' },
  { concept: 'ALS Thrombosis and Hemostasis', source: 'Hematology' },
  { concept: 'COPD 1', source: 'Pulmonology' },
  { concept: 'COPD 2', source: 'Pulmonology' },
  { concept: 'Asthma 1', source: 'Pulmonology' },
  { concept: 'Asthma 2', source: 'Pulmonology' },
  { concept: 'Lung Cancer 1', source: 'Pulmonology' },
  { concept: 'Lung Cancer 2', source: 'Pulmonology' },
  { concept: 'Lung Cancer Treatment', source: 'Pulmonology' },
  { concept: 'Tobacco Cessation', source: 'Pulmonology' },
  { concept: 'Pediatric Lung Diseases', source: 'Pulmonology' },
  { concept: 'Obstructive Sleep Apnea', source: 'Pulmonology' },
  { concept: 'Sarcoidosis', source: 'Pulmonology' },
  { concept: 'Lung Injury & Interstitial Lung Disease Pathology', source: 'Pulmonology' },
  { concept: 'Interstitial Lung Disease', source: 'Pulmonology' },
  { concept: 'Pulmonary Embolism', source: 'Pulmonology' },
  { concept: 'ARDS', source: 'Pulmonology' },
  { concept: 'Obstructive vs Restrictive PFTs', source: 'Pulmonology' }
];
